#ifndef RESOURCES_H
#define RESOURCES_H
#include "SDL_mixer.h"
#include "global.h"
#include "toolbox/toolbox.h"
typedef enum
{
  /*monsters*/
  TEX_MON_BIG_DEMON,
  TEX_MON_CHORT,
  TEX_MON_WOGOL,
  TEX_MON_IMP,
  /*jobs*/
  TEX_JOB_KNIGHT,
  TEX_JOB_WIZZARD,
  TEX_JOB_LIZZARD,
  TEX_JOB_ELF,

  /*weapons*/
  TEX_WPN_AXE,
  TEX_WPN_ANIME_SWORD,
  TEX_WPN_BOW,
  TEX_WPN_SPEAR,
  TEX_WPN_RED_STAFF,
  TEX_WPN_CLEAVER,
  TEX_WPN_KATANA,
  TEX_WPN_GOLDEN_SWORD,

  /*fx*/
  TEX_FX_BLOOD,
  TEX_FX_GOLDEN_CROSS_HIT,
  TEX_FX_BLOOD_1,
  TEX_FX_BLOOD_2,
  TEX_FX_ICE_CAST,
  TEX_FX_ICE_HIT,
  TEX_FX_FIRE_HIT,
  TEX_FX_FIRE_CAST,
  TEX_FX_SLASH,
  TEX_FX_FIRE_BUST,
  TEX_FX_HALO_EXPL,
  TEX_FX_POISONED,
  TEX_FX_FREEZZED,

  /*items*/
  TEX_ITEM_FLASK_RED_BIG,
  TEX_ITEM_FLASK_RED,
  TEX_ITEM_SCROLL,
  TEX_ITEM_KEY,
  TEX_ITEM_COIN,
  TEX_ITEM_BLUE_FLASK,

  /*chars*/
  TEX_ELITE_KNIGHT,

  /*spells*/
  TEX_RED_THUNDER,
  TEX_YELLOW_THUNDER,
  TEX_ICE_ARROW,
  TEX_FIRE_BALL,
  TEX_PURPLE_BALL,

  TEX_ARROW,
  TEX_TILESET,
  TEX_PLAYER_HEALTH_BAR,
  TEX_PONITER_DOWN,
  TEX_CHEST,
  TEX_UI_MAIN_MENU,
  TEX_UI_MAIN_MENU_POINTER,
  TEX_UI_DIALOGUE,
  TEX_DOOR,
  TEX_TILESCR_BG,
  TEX_KEYS,
  TEX_ICON_FIRE_BALL,
  TEX_ICON_ICE_ARROW,
  TEX_SPELL_FRAME,
  TEX_ICON_STAFF,
  TEX_ICON_CLEAVER,
  TEX_ICON_SPEAR,
  TEX_ICON_BOW,
  TEX_ICON_SPELL,
  TEX_ICON_CONSUMABLE,
  TEX_ICON_KEY_ITEM,
  TEX_ICON_WEAPON,
  TEX_INVENTORY,
  TEX_INVENTORY_TAB_ACTIVE,
  TEX_INVENTORY_CURSOR,
  TEX_CURSOR_POINTER,
  TEX_CURSOR_CROSS,
  TEX_EMOJI_BANG,
  TEX_EMOJI_QUESTION,
  TEX_EMOJI_SILENT,
  TEX_EMOJI_HEART,
  NUM_TEXS
} TextureId;

typedef enum
{
  BG_MUS_LV1,
  BG_MUS_LV2,
  BG_MUS_BOSS,
  BG_MUS_TILE_SCREEN,
  BG_MUS_SELECT_CHAR,
  NUM_BG_MUSICS
} BgMusId;

#define BG_MUS_ID_NULL NUM_BG_MUSICS

typedef enum
{
  FONT_DAMAGE_INDICATOR,
  FONT_ITEM_PICKED_UP,
  NUM_FONTS,
} FontId;

typedef enum
{
  SFX_SWORD_HIT,
  SFX_THUNDER,
  SFX_INTERACTION,
  SFX_CLAW_HIT,
  SFX_BUTTON,
  SFX_PUNCH,
  SFX_ICE_SHOOT,
  SFX_HIT_THUST,
  SFX_MOV_JUMP,
  SFX_WEAPON_SWORD,
  SFX_EXPOLOSION,
  SFX_FIRE_BALL_LAUCH,
  SFX_COIN,
  NUM_SFXS,
} SfxId;

#define SFX_ID_NULL NUM_SFXS

BOOL          resources_load(void);
void          resources_unload(void);
SDL_Texture*  get_texture(TextureId id);
Mix_Music*    get_bg_mus(BgMusId id);
Mix_Chunk*    get_sfx(SfxId id);
FONT*         get_font(FontId id);
Conversation* get_conversation(const char* name);
Icon          get_key_icon(u16 key);
#endif // RESOURCES_H
