#include "animations.h"
#include "resources.h"

const Animation g_anims_knight_m[] = {
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 8,
      .texture_id     = TEX_KNIGHT,
      .offset_x       = 16,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 4,
      .texture_id     = TEX_KNIGHT,
      .offset_x       = 80,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_KNIGHT,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 1,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_KNIGHT,
      .offset_x       = 96,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 1,
  },
};

const Animation g_anims_wizzard_m[] = {
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 8,
      .texture_id     = TEX_WIZZARD,
      .offset_x       = 16,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 4,
      .texture_id     = TEX_WIZZARD,
      .offset_x       = 80,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_WIZZARD,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 1,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_WIZZARD,
      .offset_x       = 96,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 1,
  },
};
const Animation g_anims_lizzard_m[] = {
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 8,
      .texture_id     = TEX_LIZZARD,
      .offset_x       = 16,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 4,
      .texture_id     = TEX_LIZZARD,
      .offset_x       = 80,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_LIZZARD,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 1,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_LIZZARD,
      .offset_x       = 96,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 1,
  },
};

const Animation g_anims_elf_m[] = {
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 8,
      .texture_id     = TEX_ELF,
      .offset_x       = 16,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 4,
      .texture_id     = TEX_ELF,
      .offset_x       = 80,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_ELF,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 1,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_ELF,
      .offset_x       = 96,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 28,
      .count          = 1,
  },
};

const Animation g_anims_chort[] = {
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 8,
      .texture_id     = TEX_CHORT,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 24,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 6,
      .texture_id     = TEX_CHORT,
      .offset_x       = 16 * 4,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 24,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 10,
      .texture_id     = TEX_CHORT,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 24,
      .count          = 1,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_CHORT,
      .offset_x       = 80,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 24,
      .count          = 1,
  },
};

const Animation g_anims_wogol[] = {
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 8,
      .texture_id     = TEX_WOGOL,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 24,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 5,
      .texture_id     = TEX_WOGOL,
      .offset_x       = 48,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 24,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 10,
      .texture_id     = TEX_WOGOL,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 24,
      .count          = 1,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_WOGOL,
      .offset_x       = 80,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 24,
      .count          = 1,
  },
};

const Animation g_anims_imp[] = {
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 8,
      .texture_id     = TEX_IMP,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 16,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 5,
      .texture_id     = TEX_IMP,
      .offset_x       = 48,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 16,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 10,
      .texture_id     = TEX_IMP,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 16,
      .count          = 1,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_IMP,
      .offset_x       = 80,
      .offset_y       = 0,
      .sprite_width   = 16,
      .sprite_height  = 16,
      .count          = 1,
  },
};

const Animation g_anims_huge_demon[] = {
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 8,
      .texture_id     = TEX_BIG_DEMON,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 32,
      .sprite_height  = 36,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 5,
      .texture_id     = TEX_BIG_DEMON,
      .offset_x       = 32 * 3,
      .offset_y       = 0,
      .sprite_width   = 32,
      .sprite_height  = 36,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 10,
      .texture_id     = TEX_BIG_DEMON,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 32,
      .sprite_height  = 36,
      .count          = 1,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_BIG_DEMON,
      .offset_x       = 32 * 5,
      .offset_y       = 0,
      .sprite_width   = 32,
      .sprite_height  = 36,
      .count          = 1,
  },
};

const Animation g_anim_fire_cast = {
  .mode           = ANIM_PLAY_MODE_NORMAL,
  .frame_duration = 1,
  .texture_id     = TEX_EFFECT_FIRE_CAST,
  .offset_x       = 0,
  .offset_y       = 0,
  .sprite_width   = 96,
  .sprite_height  = 96,
  .count          = 28,
};

const Animation g_anim_ice_cast = {
  .mode           = ANIM_PLAY_MODE_NORMAL,
  .frame_duration = 1,
  .texture_id     = TEX_EFFECT_ICE_CAST,
  .offset_x       = 0,
  .offset_y       = 0,
  .sprite_width   = 96,
  .sprite_height  = 96,
  .count          = 28,
};

const Animation g_anim_ice_arrow = {
  .mode           = ANIM_PLAY_MODE_NORMAL,
  .frame_duration = 1,
  .texture_id     = TEX_ICE_ARROW,
  .offset_x       = 0,
  .offset_y       = 0,
  .sprite_width   = 32,
  .sprite_height  = 15,
  .count          = 30,
};

const Animation g_anim_fire_ball = {
  .mode           = ANIM_PLAY_MODE_NORMAL,
  .frame_duration = 1,
  .texture_id     = TEX_FIRE_BALL,
  .offset_x       = 0,
  .offset_y       = 0,
  .sprite_width   = 26,
  .sprite_height  = 10,
  .count          = 10,
};

const Animation g_anim_fire_hit = {
  .mode           = ANIM_PLAY_MODE_NORMAL,
  .frame_duration = 1,
  .texture_id     = TEX_EFFECT_FIRE_HIT,
  .offset_x       = 0,
  .offset_y       = 0,
  .sprite_width   = 64,
  .sprite_height  = 64,
  .count          = 44,
};

const Animation g_anim_ice_hit = {
  .mode           = ANIM_PLAY_MODE_NORMAL,
  .frame_duration = 1,
  .texture_id     = TEX_EFFECT_ICE_HIT,
  .offset_x       = 0,
  .offset_y       = 0,
  .sprite_width   = 96,
  .sprite_height  = 96,
  .count          = 49,
};

const Animation g_anim_blood_loss_1 = {
  .mode           = ANIM_PLAY_MODE_NORMAL,
  .frame_duration = 1,
  .texture_id     = TEX_EFFECT_BLOOD_1,
  .offset_x       = 0,
  .offset_y       = 0,
  .sprite_width   = 100,
  .sprite_height  = 100,
  .count          = 28,
};

const Animation g_anim_blood_loss_2 = {
  .mode           = ANIM_PLAY_MODE_NORMAL,
  .frame_duration = 1,
  .texture_id     = TEX_EFFECT_BLOOD_2,
  .offset_x       = 0,
  .offset_y       = 0,
  .sprite_width   = 100,
  .sprite_height  = 100,
  .count          = 28,
};

const Animation g_anims_elite_knight[] = {
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 5,
      .texture_id     = TEX_ELITE_KNIGHT,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 32,
      .sprite_height  = 32,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_LOOP,
      .frame_duration = 5,
      .texture_id     = TEX_ELITE_KNIGHT,
      .offset_x       = 32 * 3,
      .offset_y       = 0,
      .sprite_width   = 32,
      .sprite_height  = 32,
      .count          = 4,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 10,
      .texture_id     = TEX_ELITE_KNIGHT,
      .offset_x       = 0,
      .offset_y       = 0,
      .sprite_width   = 32,
      .sprite_height  = 32,
      .count          = 1,
  },
  {
      .mode           = ANIM_PLAY_MODE_NORMAL,
      .frame_duration = 5,
      .texture_id     = TEX_ELITE_KNIGHT,
      .offset_x       = 32 * 5,
      .offset_y       = 0,
      .sprite_width   = 32,
      .sprite_height  = 32,
      .count          = 1,
  },
};

const Animation g_anim_coin = {
  .mode           = ANIM_PLAY_MODE_LOOP,
  .frame_duration = 10,
  .sprite_width   = 8,
  .sprite_height  = 8,
  .count          = 4,
  .texture_id     = TEX_COIN,
};

const Animation g_anim_slash = {
  .mode           = ANIM_PLAY_MODE_NORMAL,
  .frame_duration = 1,
  .sprite_width   = 48,
  .sprite_height  = 48,
  .count          = 10,
  .texture_id     = TEX_EFFECT_SLASH,
};
