#include "animations.h"
#include "resources.h"

const Animation g_anims_knight_m[] = {
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 8,
      .textureId     = TEX_JOB_KNIGHT,
      .offsetX       = 16,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 4,
      .textureId     = TEX_JOB_KNIGHT,
      .offsetX       = 80,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_JOB_KNIGHT,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 1,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_JOB_KNIGHT,
      .offsetX       = 96,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 1,
  },
};

const Animation g_anims_wizzard_m[] = {
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 8,
      .textureId     = TEX_JOB_WIZZARD,
      .offsetX       = 16,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 4,
      .textureId     = TEX_JOB_WIZZARD,
      .offsetX       = 80,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_JOB_WIZZARD,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 1,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_JOB_WIZZARD,
      .offsetX       = 96,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 1,
  },
};
const Animation g_anims_lizzard_m[] = {
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 8,
      .textureId     = TEX_JOB_LIZZARD,
      .offsetX       = 16,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 4,
      .textureId     = TEX_JOB_LIZZARD,
      .offsetX       = 80,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_JOB_LIZZARD,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 1,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_JOB_LIZZARD,
      .offsetX       = 96,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 1,
  },
};

const Animation g_anims_elf_m[] = {
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 8,
      .textureId     = TEX_JOB_ELF,
      .offsetX       = 16,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 4,
      .textureId     = TEX_JOB_ELF,
      .offsetX       = 80,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_JOB_ELF,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 1,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_JOB_ELF,
      .offsetX       = 96,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 28,
      .count         = 1,
  },
};

const Animation g_anims_chort[] = {
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 8,
      .textureId     = TEX_MON_CHORT,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 24,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 6,
      .textureId     = TEX_MON_CHORT,
      .offsetX       = 16 * 4,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 24,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 10,
      .textureId     = TEX_MON_CHORT,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 24,
      .count         = 1,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_MON_CHORT,
      .offsetX       = 80,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 24,
      .count         = 1,
  },
};

const Animation g_anims_wogol[] = {
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 8,
      .textureId     = TEX_MON_WOGOL,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 24,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 5,
      .textureId     = TEX_MON_WOGOL,
      .offsetX       = 48,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 24,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 10,
      .textureId     = TEX_MON_WOGOL,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 24,
      .count         = 1,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_MON_WOGOL,
      .offsetX       = 80,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 24,
      .count         = 1,
  },
};

const Animation g_anims_imp[] = {
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 8,
      .textureId     = TEX_MON_IMP,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 16,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 5,
      .textureId     = TEX_MON_IMP,
      .offsetX       = 48,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 16,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 10,
      .textureId     = TEX_MON_IMP,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 16,
      .count         = 1,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_MON_IMP,
      .offsetX       = 80,
      .offsetY       = 0,
      .spriteWidth   = 16,
      .spriteHeight  = 16,
      .count         = 1,
  },
};

const Animation g_anims_huge_demon[] = {
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 8,
      .textureId     = TEX_MON_BIG_DEMON,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 32,
      .spriteHeight  = 36,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 5,
      .textureId     = TEX_MON_BIG_DEMON,
      .offsetX       = 32 * 3,
      .offsetY       = 0,
      .spriteWidth   = 32,
      .spriteHeight  = 36,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 10,
      .textureId     = TEX_MON_BIG_DEMON,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 32,
      .spriteHeight  = 36,
      .count         = 1,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_MON_BIG_DEMON,
      .offsetX       = 32 * 5,
      .offsetY       = 0,
      .spriteWidth   = 32,
      .spriteHeight  = 36,
      .count         = 1,
  },
};

const Animation g_anim_fire_cast = {
  .mode          = ANIM_PLAY_MODE_NORMAL,
  .frameDuration = 1,
  .textureId     = TEX_FX_FIRE_CAST,
  .offsetX       = 0,
  .offsetY       = 0,
  .spriteWidth   = 96,
  .spriteHeight  = 96,
  .count         = 28,
};

const Animation g_anim_ice_cast = {
  .mode          = ANIM_PLAY_MODE_NORMAL,
  .frameDuration = 1,
  .textureId     = TEX_FX_ICE_CAST,
  .offsetX       = 0,
  .offsetY       = 0,
  .spriteWidth   = 96,
  .spriteHeight  = 96,
  .count         = 28,
};

const Animation g_anim_ice_arrow = {
  .mode          = ANIM_PLAY_MODE_NORMAL,
  .frameDuration = 1,
  .textureId     = TEX_ICE_ARROW,
  .offsetX       = 0,
  .offsetY       = 0,
  .spriteWidth   = 32,
  .spriteHeight  = 15,
  .count         = 30,
};

const Animation g_anim_fire_ball = {
  .mode          = ANIM_PLAY_MODE_NORMAL,
  .frameDuration = 1,
  .textureId     = TEX_FIRE_BALL,
  .offsetX       = 0,
  .offsetY       = 0,
  .spriteWidth   = 26,
  .spriteHeight  = 10,
  .count         = 10,
};

const Animation g_anim_fire_hit = {
  .mode          = ANIM_PLAY_MODE_NORMAL,
  .frameDuration = 1,
  .textureId     = TEX_FX_FIRE_HIT,
  .offsetX       = 0,
  .offsetY       = 0,
  .spriteWidth   = 64,
  .spriteHeight  = 64,
  .count         = 44,
};

const Animation g_anim_ice_hit = {
  .mode          = ANIM_PLAY_MODE_NORMAL,
  .frameDuration = 1,
  .textureId     = TEX_FX_ICE_HIT,
  .offsetX       = 0,
  .offsetY       = 0,
  .spriteWidth   = 96,
  .spriteHeight  = 96,
  .count         = 49,
};

const Animation g_anim_blood_loss_1 = {
  .mode          = ANIM_PLAY_MODE_NORMAL,
  .frameDuration = 1,
  .textureId     = TEX_FX_BLOOD_1,
  .offsetX       = 0,
  .offsetY       = 0,
  .spriteWidth   = 100,
  .spriteHeight  = 100,
  .count         = 28,
};

const Animation g_anim_blood_loss_2 = {
  .mode          = ANIM_PLAY_MODE_NORMAL,
  .frameDuration = 1,
  .textureId     = TEX_FX_BLOOD_2,
  .offsetX       = 0,
  .offsetY       = 0,
  .spriteWidth   = 100,
  .spriteHeight  = 100,
  .count         = 28,
};

const Animation g_anims_elite_knight[] = {
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 10,
      .textureId     = TEX_ELITE_KNIGHT,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 32,
      .spriteHeight  = 32,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_LOOP,
      .frameDuration = 5,
      .textureId     = TEX_ELITE_KNIGHT,
      .offsetX       = 32 * 3,
      .offsetY       = 0,
      .spriteWidth   = 32,
      .spriteHeight  = 32,
      .count         = 4,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 10,
      .textureId     = TEX_ELITE_KNIGHT,
      .offsetX       = 0,
      .offsetY       = 0,
      .spriteWidth   = 32,
      .spriteHeight  = 32,
      .count         = 1,
  },
  {
      .mode          = ANIM_PLAY_MODE_NORMAL,
      .frameDuration = 5,
      .textureId     = TEX_ELITE_KNIGHT,
      .offsetX       = 32 * 5,
      .offsetY       = 0,
      .spriteWidth   = 32,
      .spriteHeight  = 32,
      .count         = 1,
  },
};

const Animation g_anim_coin = {
  .mode          = ANIM_PLAY_MODE_LOOP,
  .frameDuration = 10,
  .spriteWidth   = 8,
  .spriteHeight  = 8,
  .count         = 4,
  .textureId     = TEX_ITEM_COIN,
};

const Animation g_anim_slash = {
  .mode          = ANIM_PLAY_MODE_NORMAL,
  .frameDuration = 1,
  .spriteWidth   = 48,
  .spriteHeight  = 48,
  .count         = 10,
  .textureId     = TEX_FX_SLASH,
};
